import{a as E,S as v,i}from"./assets/vendor-F7a2Vas_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const A="https://pixabay.com/api/",S="52282020-0fa7caca98833a1caa1732196";async function h(e,r=1){const o={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await E.get(A,{params:o})).data}catch(n){throw console.error("Error fetching images:",n),n}}const g=document.querySelector(".gallery"),u=document.querySelector(".loader");let a=null;const q=document.querySelector(".form"),c=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){if(!Array.isArray(e)||e.length===0)return;const r=e.map(o=>`
<li class="gallery__item">
  <a class="gallery__link" href="${o.largeImageURL}">
    <img class="gallery__image" src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${o.likes}</span></p>
    <p class="info-item"><b>Views</b><span>${o.views}</span></p>
    <p class="info-item"><b>Comments</b><span>${o.comments}</span></p>
    <p class="info-item"><b>Downloads</b><span>${o.downloads}</span></p>
  </div>
</li>`).join("");g.insertAdjacentHTML("beforeend",r),M.refresh()}function _(){g.innerHTML=""}function L(e="form"){u&&(u.style.display="flex"),a&&a.remove(),a=document.createElement("p"),a.classList.add("loader-text"),a.textContent="Loading images, please wait...",e==="form"?q.insertAdjacentElement("afterend",a):e==="loadMore"&&c.insertAdjacentElement("afterend",a),a.style.display="block"}function f(){u&&(u.style.display="none"),a&&(a.remove(),a=null)}function w(){c&&(c.style.display="block")}function y(){c&&(c.style.display="none")}function B(){return c}const x=document.querySelector(".form");let d="",l=1,p=0;const P=B();x.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.target["search-text"].value.trim(),!d){i.warning({title:"Warning",message:"Please enter a search query."});return}l=1,_(),y(),L("form");try{const r=await h(d,l);if(f(),!r||!Array.isArray(r.hits)||r.hits.length===0){i.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}p=r.totalHits,b(r.hits),l*15<p?w():(y(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(r){f(),i.error({title:"Error",message:"An error occurred while fetching images."}),console.error(r)}});P.addEventListener("click",async()=>{l+=1,y(),L("loadMore");try{const e=await h(d,l);if(f(),e.hits.length){b(e.hits);const r=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),l*15<p?w():(y(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}}catch(e){f(),i.error({title:"Error",message:"An error occurred while fetching more images."}),console.error(e)}});
//# sourceMappingURL=index.js.map
